### ISSUE TITLE
Photos or Videos Are Not Downloading

### ISSUE THREAD

**Issue by nikotidar** [haoict/instagram-no-ads#14]
Hi, there! I'm a big fans of your tweaks. Here's the detail:

* iPhone Xr
* iOS 13.5 Jailbroken with unc0ver
* Instagram version = 1.58.1
* Instagram No Ads version = Latest

Here's the screenshot

![image](https://user-images.githubusercontent.com/49534825/92979216-27623d00-f4bc-11ea-9fca-544fae02f62b.png)

**Comment by haoict** [comment]
Could you please update the tweak and check again?
I'll close this issue, please reopen if the issue is persistent

**Comment by nikotidar** [comment]
Fixed now! Thanks for your awesome tweaks, pal!😀
