### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by vampir551** [haoict/instagram-no-ads#17]
Dont work. Iphone xr ios 13,5. Why? 
![4BFF5208-F1DB-4A60-BA6C-ECC5EA22DB6E](https://user-images.githubusercontent.com/22983275/103827071-34b5bf80-5089-11eb-824e-d547003c5890.png)
![66F44BD2-CCC2-471C-9124-EAF5D2323F92](https://user-images.githubusercontent.com/22983275/103827111-4b5c1680-5089-11eb-8194-a86e6d3b3b5e.png)

**Comment by haoict** [comment]
Close due to no detail information
