### ISSUE TITLE
Not working on v143.0

### ISSUE THREAD

**Issue by pzumk** [haoict/instagram-no-ads#3]
Hi, it doesn’t seem to work on Instagram v143.0 - is it possible to fix this?

**Comment by haoict** [comment]
Just tested on my devices with Instagram v143.0, still working fine.
If you have any jailbreak bypass tweak (UnSub, FlyJB), try to whitelist my tweak.

**Comment by pzumk** [comment]
I’ve had Choicy and Shadow installed. Removed both, still doesn’t work unfortunately. I don’t have any other tweaks for IG installed.

**Comment by haoict** [comment]
Please follow these instructions:

1. Install FLEXing from BigBoss: https://moreinfo.thebigboss.org/moreinfo/depiction.php?file=flexingDp
2. Respring after installing
3. Open Instagram
4. Hold on the Status Bar to open the FLEX toolbar
5. Tap the "Menu" button
6. Tap "Runtime Browser"
7. Search for "instanoads"
8. Does "instanoads.dylib" appear?

If yes: Please share your twitter account, or you can add me at https://twitter.com/haoict. I will DM you to follow up and debug

If no: seems like there is problem with your device, it can not load the tweak, not the problem with the tweak itself.

**Comment by pzumk** [comment]
It appears, but when tapping on it it shows “0 Classes”. Sent you a tweet, same username as on github. Feel free to DM me, DMs are open
